name: Main

on:
  pull_request:
    branches:
    - main  
  push:
    branches:
    - main
    tags:
    - "*.*.*"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: cargo test

  release:
    name: Release
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Create release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/yeah

    - name: Publish
      continue-on-error: true
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
